### PR TITLE
added tooltip to sliders with allowOutOfBounds=true

### LINKED ISSUE #65: [Suggestion] Add tooltip to sliders with allowOutOfBounds=true
### Describe the feature

It is unintuitive that you need to CTRL + click in order to set an arbitrary number. It would be beneficial to add a tooltip when hovering in order to inform users of that feature.

### Before submitting a suggestion

- [X] This feature doesn't already exist.
(I have checked the source on the **latest build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

### PR DESCRIPTION
**Pull request by Lyzev**
there is a tooltip for every slider now

1. allowOutOfBounds=true
image

2. allowOutOfBounds=false
image

close #65

### CODE REVIEW

**Review by Redstonecrafter0 — CHANGES_REQUESTED** [review]
This makes line 49 redundant and ignores the previously shown desc. It would be better to merge these two lines and also show the desc of the setting.

**Comment by Lyzev** [comment]
> This makes line 49 redundant and ignores the previously shown desc. It would be better to merge these two lines and also show the desc of the setting.

the tooltip description is displayed when the mouse pointer is moved over the label, as before

**Review by Redstonecrafter0 — APPROVED** [review]
looks fine. imgui has an unclear API to me.

**Comment by Lyzev** [comment]
> looks fine. imgui has an unclear API to me.

You acquire knowledge over time, don't give up if you don't understand something straight away ;)

**Pull request merged**
